//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastodonObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MastodonObserver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Mastodon連携 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_CATEGORY_MSTDN {
            get {
                return ResourceManager.GetString("SETTING_CATEGORY_MSTDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントのID
        ///ex) ProgrammerGenboo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_ACCOUNTID {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_ACCOUNTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   02)アカウントID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_ACCOUNTID_LABEL {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_ACCOUNTID_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インスタンスのURL
        ///ex) https://mstdn.y-zu.org に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_INSTANCEURL {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_INSTANCEURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   01)インスタンスURL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_INSTANCEURL_LABEL {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_INSTANCEURL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントに紐付けられたトークン
        ///(settings/applicationより作成) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_TOKEN {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   03)トークン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SETTING_MSTDN_BASIC_TOKEN_LABEL {
            get {
                return ResourceManager.GetString("SETTING_MSTDN_BASIC_TOKEN_LABEL", resourceCulture);
            }
        }
    }
}
